---
x-honcho-common:
  &honcho-common
  build:
    context: .
    dockerfile: docker/Dockerfile.honcho
  links:
    - database
  networks:
    - isolated
  volumes:
    - ./config/honcho/config.toml:/app/config.toml

  honcho-db-migrations:
    container_name: honcho-migrations
    <<: *honcho-common
    entrypoint: ["/app/.venv/bin/python", "scripts/provision_db.py"]
    depends_on:
      database:
        condition: service_healthy

  honcho:
    container_name: honcho-api
    <<: *honcho-common
    entrypoint: ["/app/.venv/bin/fastapi", "run", "--host", "0.0.0.0", "src/main.py"]
    ports:
      - "8000:8000"
    depends_on:
      honcho-db-migrations:
        condition: service_completed_successfully

  deriver:
    container_name: honcho-driver
    <<: *honcho-common
    entrypoint: ["/app/.venv/bin/python", "-m", "src.deriver"]
    depends_on:
      honcho-db-migrations:
        condition: service_completed_successfully

  database:
    container_name: honcho-database
    image: registry.poppet.io/dockerhub/pgvector/pgvector:pg15
    restart: unless-stopped
    command: ["postgres", "-c", "max_connections=200"]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - honcho-pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - isolated

volumes:
  honcho-pgdata:
